version: "3"

services:
  elasticsearch:
    image: elasticsearch:${VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      # Data 
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk-net

  kibana:
    image: kibana:${VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - "I18N_LOCALE=${KIBANA_LOCALE}"
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elk-net

  logstash:
    image: logstash:${VERSION}
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      # Pipeline
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # Index Template
      - ./logstash/template:/usr/share/logstash/template
      # Input Data
      - ./logstash/input/httpd:${LOGSTASH_INPUT_DATA_PATH}
    networks:
      - elk-net

volumes:
  elasticsearch-data:

networks:
  elk-net:
